from dataclasses import dataclass


@dataclass
class CodeContext:
    step_n: int
    task: str
    num_rounds: int = 4
    time_out: int = 60
    constraints: str = """
    All data files generated by the script must be saved to the data_dir shown below:
    from pathlib import Path
    DATA_DIR = Path(__file__).resolve().parent.parent / "data"
    """